# Generated by Django 5.2.13 on 2026-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('tipos', models.CharField(max_length=40)),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
